name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Start minikube and build images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Try cluster
        run: kubectl get pods -A

      - name: Build Images
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker compose build
          echo -n "Verifying images: "
          docker images
          echo "Images build successfully"

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.24.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/kompose

      - name: Deploy to minikube
        run: |
          kompose convert
          kubectl apply -f backend-deployment.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f backend-service.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f frontend-deployment.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f frontend-service.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f postgres-deployment.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f postgres-data-persistentvolumeclaim.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f postgres-service.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl get all
          sleep 50
          echo "Successfully deployed!"
          kubectl get all
      - name: Test backend service URLs
        run: |
          echo "SERVICE_URL=$(minikube service backend --url)"
          kubectl port-forward service/backend 8080:8080 &> /dev/null &
          sleep 5
          curl -i http://localhost:8080/departments/1

      - name: Test frontend service URLs
        run: |
          echo "SERVICE_URL=$(minikube service frontend --url)"
          kubectl port-forward service/frontend 3000:3000 &> /dev/null &
          sleep 5
          curl -i http://localhost:3000/

      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete
