name: CI

on:
  workflow_dispatch:  # Manually trigger workflow runs
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest  # Run on Ubuntu using the latest version

    steps:
      - name: Check-out your repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test
        run: |
             ls -al
             cd assignment-doc-backend
             mvn -B test
