name: CI
on:
  push:
    branches: [ main ]

jobs:
  tests-backend:
    name: Backend(java) Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check-out your repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test
        run: |
             ls -al
             cd assignment-doc-backend
             mvn -B test

  tests-frontend:
    name: Frontend(react) Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
              cd assignment-doc-frontend
              npm install
      - name: Run tests
        run: |
             cd assignment-doc-frontend
             npm test
